# -*- coding: utf-8 -*-
{
    "name": "Dynamic Financial Report Wizards",
    "version": "18.0.1.0.0",
    "category": "Tools",
    "summary": "Auto-generated module",
    "description": "This is an autogenerated module scaffold.",
    "author": 'Your Company',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',
    "depends": ["base","dynamic_accounts_report"],
    "data": [
    "views/menu_items.xml",
    "wizards/wiz_account_general_ledger.xml"
    ],
    "assets": {
        'web.assets_backend': [
            'dynamic_financial_report_wizards/static/src/js/general_ledger.js',
        ],
    },
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}