# -*- coding: utf-8 -*-
{
    'name': 'CloudAppify - Dynamic Account Reports',
    'version': '16.0.1.0.1',
    'category': 'CloudAppify',
    'summary': 'This is based on the report dynamic_acocunts_report of Cybrosystem',
    'description': "Dynamic Financial Reports, DynamicFinancialReports, FinancialReport, Accountingreports, odoo reports, odoo"
                   "This module creates dynamic Accounting General Ledger, Trial Balance, Balance Sheet "
                   "Proft and Loss, Cash Flow Statements, Partner Ledger,"
                   "Partner Ageing, Day book"
                   "Bank book and Cash book reports in Odoo 14 community edition.",
    'author': 'Cybrosys Techno Solutions',
    'maintainer':'James Michael ortiz',
    'website': 'cloudappify.com',
    'depends': ['base', 'base_accounting_kit'],
    'data': [
        'security/ir.model.access.csv',
        'views/templates.xml',
        'views/views.xml',
        'views/kit_menus.xml',
        'views/reports_config_view.xml',
        'wizard/general_ledger.xml',
        'wizard/cash_flow.xml',
        'wizard/balance_sheet.xml',
        'wizard/profit_and_loss.xml',
        'wizard/bank_book.xml',
        'wizard/trial_balance.xml',
        'report/trial_balance.xml',
        'report/general_ledger.xml',
        'report/cash_flow_report.xml',
        'report/financial_report_template.xml',
        'report/partner_ledger.xml',
        'report/ageing.xml',
        'report/daybook.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ca_dynamic_accounts_report/static/src/css/report.css',
            'ca_dynamic_accounts_report/static/src/js/action_manager.js',
            'ca_dynamic_accounts_report/static/src/js/general_ledger.js',
            'ca_dynamic_accounts_report/static/src/js/trial_balance.js',
            'ca_dynamic_accounts_report/static/src/js/cash_flow.js',
            'ca_dynamic_accounts_report/static/src/js/financial_reports.js',
            'ca_dynamic_accounts_report/static/src/js/partner_ledger.js',
            'ca_dynamic_accounts_report/static/src/js/ageing.js',
            'ca_dynamic_accounts_report/static/src/js/daybook.js',
            'ca_dynamic_accounts_report/static/src/xml/general_ledger_view.xml',
            'ca_dynamic_accounts_report/static/src/xml/trial_balance_view.xml',
            'ca_dynamic_accounts_report/static/src/xml/cash_flow_view.xml',
            'ca_dynamic_accounts_report/static/src/xml/financial_reports_view.xml',
            'ca_dynamic_accounts_report/static/src/xml/partner_ledger_view.xml',
            'ca_dynamic_accounts_report/static/src/xml/ageing.xml',
            'ca_dynamic_accounts_report/static/src/xml/daybook.xml',
        ],
    },
    'license': 'LGPL-3',
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
    'application': False,
    'post_init_hook': '_load_account_details_post_init_hook',
    'uninstall_hook': 'unlink_records_financial_report'
}